server:
  port: 8661

spring:
  application:
    name: cloud-cunsumer-order-service
  datasource:
    # 当前数据源操作类型
    type: com.alibaba.druid.pool.DruidDataSource
    # mysql驱动类
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://101.200.58.119:3306/cloud2?serverTimezone=UTC&characterEncoding=utf8&useUnicode=true&useSSL=false&allowMultiQueries=true
    username: root
    password: Jt!!2018

eureka:
  client:
    #false表示不向注册中心注册自己
    register-with-eureka: false
    service-url:
      #设置与Eureka Server交互的地址查询服务和注册服务都需要依赖这个地址
      #单机版
      #      defaultZone: http://${eureka.instance.hostname}:7001/eureka
      #集群版，注册地址以逗号隔开
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka

ribbon:
  #http建立socket超时时间，毫秒
  ConnectTimeout: 60000
  #http读取响应socket超时时间
  ReadTimeout: 60000

mybatis:
  mapper-locations: classpath*:mapper/*.xml
  type-aliases-package: com.jt.springcloud.entities

logging:
  level:
    com.jt.springcloud.service.PaymentFeignService: debug