server:
  port: 9661

spring:
  application:
    name: nacos-order-consumer
  datasource:
    # 当前数据源操作类型
    type: com.alibaba.druid.pool.DruidDataSource
    # mysql驱动类
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/cloud?serverTimezone=UTC&characterEncoding=utf8&useUnicode=true&useSSL=false&allowMultiQueries=true
    username: root
    password: 123456
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848 #配置nacos地址
service-url:
  nacos-user-service: http://nacos-payment-provider
mybatis:
  mapper-locations: classpath*:mapper/*.xml
  type-aliases-package: com.jt.springcloud.entities