server:
  port: 9661

spring:
  application:
    name: nacos-order-consumer
  datasource:
    # 当前数据源操作类型
    type: com.alibaba.druid.pool.DruidDataSource
    # mysql驱动类
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/cloud?serverTimezone=UTC&characterEncoding=utf8&useUnicode=true&useSSL=false&allowMultiQueries=true
    username: root
    password: 123456
  redis:
    cluster:
      nodes:
        - 192.168.31.33:6379
#        - 192.168.31.180:6379
#        - 192.168.31.201:6379
    password: # 密码（默认为空）
    timeout: 6000  # 连接超时时长（毫秒）
    jedis:
      pool:
        max-active: 1000  # 连接池最大连接数（使用负值表示没有限制）
        max-wait: -1ms      # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-idle: 10      # 连接池中的最大空闲连接
        min-idle: 5       # 连接池中的最小空闲连接
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848 #配置nacos地址
service-url:
  nacos-user-service: http://nacos-payment-provider
mybatis:
  mapper-locations: classpath*:mapper/*.xml
  type-aliases-package: com.jt.springcloud.entities