server:
  port: 8002

spring:
  application:
    name: cloud-payment-service
  datasource:
    # 当前数据源操作类型
    type: com.alibaba.druid.pool.DruidDataSource
    # mysql驱动类
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://101.200.58.119:3306/cloud?serverTimezone=UTC&characterEncoding=utf8&useUnicode=true&useSSL=false&allowMultiQueries=true
    username: root
    password: Jt!!2018

eureka:
  instance:
    hostname: localhost
  client:
    #true表示向注册中心注册自己
    register-with-eureka: true
    #true表示自己端就是注册中心，职责就是维护服务实例，并不需要去检索服务
    fetch-registry: true
    service-url:
      #设置与Eureka Server交互的地址查询服务和注册服务都需要依赖这个地址
      #单机版
#      defaultZone: http://${eureka.instance.hostname}:7001/eureka
      #集群版，注册地址以逗号隔开
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka

mybatis:
  mapper-locations: classpath*:mapper/*.xml
  type-aliases-package: com.jt.springcloud.entities