server:
  port: 8014

spring:
  application:
    name: cloud-payment-nacos-service2
  datasource:
    # 当前数据源操作类型
    type: com.alibaba.druid.pool.DruidDataSource
    # mysql驱动类
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://101.200.58.119:3306/cloud?serverTimezone=UTC&characterEncoding=utf8&useUnicode=true&useSSL=false&allowMultiQueries=true
    username: root
    password: Jt!!2018
  cloud:
    nacos:
      discovery:
        server-addr: 123.57.217.100:8848

mybatis:
  mapper-locations: classpath*:mapper/*.xml
  type-aliases-package: com.jt.springcloud.entity